### ISSUE TITLE
.sql style, DateTime2 parameters not working

### ISSUE THREAD

**Issue by wballard** [igroff/epiquery2#32]
two isseus, there are 'aliases' in Tedious types. Tedious, so it ends up being datetime2n. No foolin.

Then -- you go and pass moment or Date, and you get an invalid parameter value.

**Comment by igroff** [comment]
It would appear Tedious expects datetime* params to receive a javascript Date object, there is no implicit conversion... Which is unfortunate, I'm fixing it.
